version:"3"
services:
  api-gateway:
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - chat-service
      - users-service
    ports:
      - "7000:7000"
      volumes:
        - "./api-gateway/config:/config"
        - "./api-gateway/logs:/logs"